### ISSUE TITLE
repository not found

### ISSUE THREAD

**Issue by jenya87** [laudis-technologies/neo4j-php-client#10]
Hello! I use php 7.4.13 and I try to install your package with composer. So, during the installation I have an error:
```
Cloning into 'neo4j-php-client'...
info: please complete authentication in your browser... // I do this successfully, I have a token from github
remote: Repository not found.
fatal: repository 'https://github.com/transistive/neo4j-php-client.git/' not found
```
Please help.

**Comment by transistive** [comment]
Dear Jenya,

Thank you for submitting this issue. Since I was under the assumption that almost no one was using this library at the time, I made a hard reset and started the count from version 1.0 instead of building on top of the graphaware client.

Long story short: Make sure you are using version 1.0 in your composer.json file. This can be done swiftly with these two commands:
- `composer remove laudis/neo4j-php-client`
- `composer require laudis/neo4j-php-client`

Or by simply changing the version in your composer.json file to this: `"laudis/neo4j-php-client": "^1.0"` and then running `composer update`.

Please report if this fixes the issue or not, so we can either close the issue or continue problem-solving.

Kind regards,
Ghlen

**Comment by jenya87** [comment]
I do it, and  unfortunatly, I have another error:
```
    Now trying to download from source
  - Syncing laudis/neo4j-php-client (1.0.0) into cache
info: please complete authentication in your browser...

 1/1 [============================] 100%
Installation failed, reverting ./composer.json and ./composer.lock to their orig
inal content.


  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "git clone --mirror "https://github.com/transistive/neo4j-php-c
  lient.git" "C:/Users/user/AppData/Local/Composer/vcs/https---github.com-tra
  nsistive-neo4j-php-client.git/"" exceeded the timeout of 300 seconds.
```

**Comment by transistive** [comment]
No problem, I assume this is going to be a caching issue as I double-checked and it works on my end.
Try these steps in order

1. delete the composer.lock file
2. run `composer clearcache`
3. remove the line in your composer.json file which contains this line: "laudis/neo4j-php-client": "^1.0"
4. run `composer update`
5. run `composer require laudis/neo4j-php-client`

If that still does not work I am going to need you to copy and paste the contents of the composer.json file and attach the command you used to install the package.

Best of luck,
Ghlen

**Comment by transistive** [comment]
Hi Jenya,
I took another hard look and found out I made a misconfiguration on packagist. This is the reason for the error. My apologies for the inconvenience. It should work now :+1: 
Greetings,
Ghlen

**Comment by jenya87** [comment]
Hello, **transistive** . Thank you for improovments! I successfully install your package in my laravel project, connect to neo server and get some records. Works great!
And what about a visual graph representation of query results? As I understand, you are planning to implemet it in future version?
But now, can  I visualize query results as graph with color nodes (like neo4j browser) in my laravel application? Are there any .js libs to do this?
Thanks.

**Comment by transistive** [comment]
Hi Jenya,

I am glad you like it. Sadly this is a PHP library. The graph representation I am working on will never contain .js solution. It will be an object-oriented, PHP only solution. There is however an example I made that works with the d3.js library to present some movies. That might push you in the right direction. It can be found [here](https://github.com/neo4j-examples/movies-neo4j-php-client). A clone of the end result can be found [here](http://my-neo4j-movies-app.herokuapp.com/).

I am however going to close this issue. If you want to continue this discussion you can always open a new one as we have now left the scope of the initial issue.

Best of luck!
Ghlen
