### ISSUE TITLE
Neo.ClientError.Database.DatabaseNotFound

### ISSUE THREAD

**Issue by jenya87** [laudis-technologies/neo4j-php-client#15]
Hello! I use Neo4j commynity edition 4.0.4.
Is there any option to set default database name in your package? Because I change default ```neo4j``` db to my own, and I have an error:
```
Neo4j errors detected. First one with code "Neo.ClientError.Database.DatabaseNotFound" 
and message "The database requested does not exists. Requested database name: 'neo4j'."
```
Thanks!

**Comment by transistive** [comment]
Hello,

Yes, there is an option! You can use the HttpInjections or BoltInjections respectively while using the client builder. Here is an example:

```php
$client = Laudis\Neo4j\ClientBuilder::create()
    ->addHttpConnection('http', 'http://neo4j:password@localhost', HttpInjections::create()->withDatabase('myDatabase'))
    ->addBoltConnection('bolt', 'neo4j:password@localhost', BoltInjections::create()->withDatabase('tags'))
    ->build();
```

**Comment by jenya87** [comment]
Works greate, thanks! 
But how annoying to switch between db's in community edition of Neo :)

**Comment by transistive** [comment]
Yeah, it's not so simple but I am glad I could be of help!
Best of luck
