### ISSUE TITLE
Cannot handle objects without a properties method

### ISSUE THREAD

**Issue by va5ja** [laudis-technologies/neo4j-php-client#20]
I'm trying to find the shortest path with:
```
MATCH (a:Node {}), (b:Node {}), p = shortestPath((a)-[*]-(b)) RETURN p
```
but I'm getting error:
```
Cannot handle objects without a properties method. Class given: Bolt\structures\Path
```

Are these kind of operations supported?

**Comment by va5ja** [comment]
I found out that it works over Http Connection but not over Bolt Connection.

**Comment by transistive** [comment]
Thank you, I have figured out the problem and am working on a solution for bolt. It shouldn't take too long to fix this.

**Comment by transistive** [comment]
Hello va5ja,

Thank you for being patient; I was quite busy. The relationship types now properly get translated. Please update to version 1.1.2 if you wish to use it.

Have a good day,
Ghlen

**Comment by va5ja** [comment]
That's great, thank you!
