### ISSUE TITLE
Bolt connection doesn't always work

### ISSUE THREAD

**Issue by jonathan-rowley** [laudis-technologies/neo4j-php-client#29]
I am trying to use the Bolt protocol for my queries and for whatever reason it only works for some queries and I cannot figure out a pattern.

so far my http connections are working without error and bolt works for some queries but not all.

I have noticed that using ```MATCH p=()-[]->() RETURN p; ``` fails so instead I use ```MATCH (p)-[r]->(s) RETURN p,r,s; ``` and it works.

The error I get when I use bolt is:
```bash
PHP Fatal error:  Uncaught Bolt\error\ConnectException: Read error in /web-root/vendor/stefanak-michal/bolt/src/connection/StreamSocket.php:97
Stack trace:
#0 /web-root/vendor/stefanak-michal/bolt/src/protocol/AProtocol.php(93): Bolt\connection\StreamSocket->read()
#1 /web-root/vendor/stefanak-michal/bolt/src/protocol/V4.php(39): Bolt\protocol\AProtocol->read()
#2 /web-root/vendor/stefanak-michal/bolt/src/protocol/V4.php(25): Bolt\protocol\V4->pull()
#3 /web-root/vendor/stefanak-michal/bolt/src/Bolt.php(274): Bolt\protocol\V4->pullAll()
#4 /web-root/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php(130): Bolt\Bolt->pullAll()
#5 /web-root/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php(57): Laudis\Neo4j\Network\Bolt\BoltSession->runStatements()
#6 /web-root/vendor/laudis/neo4j-php-client/src/Client.php(54): Laudis\Neo4j\Network\Bolt\BoltSession->run()
#7 /web-root/vendor/laudis/neo4j-php-client/src/Client.php(46): Laudis\Neo4j\Client->r in /web-root/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php on line 132
```

My connection settings are:
```php
$this->conn = Laudis\Neo4j\ClientBuilder::create()
            ->addHttpConnection("http", 'http://'.$configs->user.':'.$configs->password.'@'.$configs->database)
            ->addBoltConnection("neo4j", 'neo4j+ssc://'.$configs->user.':'.$configs->password.'@'.$configs->database)
            ->addBoltConnection("bolt", 'bolt://'.$configs->user.':'.$configs->password.'@'.$configs->database)
            ->setDefaultConnection("bolt")
            ->build();
```

I get the same errors with the "neo4j" and "bolt" connections.

I tried using the runStatements() method but it wont allow me to differentiate between protocols which i understand. So instead I had to run individual statements:
```php
$titleQuery = "
            MATCH (t:Title)-[:TITLE_OF]->(v:Video)-[:CATEGORY_OF]->(c:Category) 
            WHERE $fuzzyTitleBuild $categories 
            RETURN DISTINCT
            t.title as title,
            c.category AS category,
            v.assetId AS assetId,
            v.publishDate AS publishDate,
            v.allText AS allText;
        ";
      
$imageTagQuery = "
            MATCH (v2:Video)<-[vr2:RECOGNIZED]-(i2:Image)<-[it2:IMAGE_TAG]-(t:Tag)-[it1:IMAGE_TAG]->(i1:Image)-[vr1:RECOGNIZED]->(v1:Video {assetId: '$searchAssetId'}),
            (i2)-[oa2:OCCURS_AT]->(o2:Occurrence),
            (v2)-[:CATEGORY_OF]->(c:Category)
            WHERE 
            v2.assetId <> v1.assetId
            $categories
            RETURN DISTINCT
            COLLECT([t.tag,it2.score,o2.timestamp,o2.length]) AS tag_score_timestamp_length,
            COUNT(DISTINCT t.tag) AS tagMatchCount,
            c.category AS category,
            v2.title AS title,
            v2.assetId AS assetId,
            v2.publishDate AS publishDate,
            v2.allText AS allText
            ORDER BY tagMatchCount DESC;
        ";
$titleMatch = $this->conn->run($titleQuery,[],"bolt"); // works fine on bolt and http

$imageTagMatch = $this->conn->run($imageTagQuery,[],"http"); //only works on http and I'm not sure why
```

I have already updated my neo4j-php-client to the latest version and still has the same issue. (Current version: 1.1.4)
My Neo4j version is 4.1.3 with a Casual Cluster.

I will have to settle with specifying protocol with each query for now but since i couldn't find any help about this issue on the internet i figured i would let someone know.

UPDATE: I suspect it has to do with the return. Perhaps it has difficulties cleaning some of the characters using the Bolt protocol but I got different results from using some parameters in the same query vs others and I see the spike on the server CPU with each request which tells me that the database is processing the request.

**Comment by jonathan-rowley** [comment]
ok, I think I have narrowed it down a bit further and it is breaking on Michal Stefanak's package. it would seem that there are special characters being returned from my DB and it is not being handled. It seems like it should be since the Neo4j DB accepts it. I am still looking into it but figured i would leave an update here.

/src/protocol/AProtocol.php
```php
/**
 * Abstract class AProtocol
 *
 * @author Michal Stefanak
 * @link https://github.com/stefanak-michal/Bolt
 * @package Bolt\protocol
 */

...

    protected function read(?int &$signature)
    {
        $msg = '';
        while (true) {
            $header = $this->connection->read(2);
            if (ord($header[0]) == 0x00 && ord($header[1]) == 0x00)
                break;
            $length = unpack('n', $header)[1] ?? 0;
            $msg .= $this->connection->read($length);
        }

        $output = null;
        $signature = 0;
        if (!empty($msg)) {
            $output = $this->unpacker->unpack($msg, $signature); // This is where the issue fails to interpret the chars
        }

        return $output;
    }
```

**Comment by transistive** [comment]
Hello Jonathan,

Thank you for taking the time to post this issue. Could you paste the result returned over the HTTP request? That way, we can take see if we can reproduce the issue and narrow down the characters. Then we can bring over the issue to Stefanak's package. In the meantime, I might provide a small and hacky patch to keep things running.

Best of luck,

Ghlen

**Comment by jonathan-rowley** [comment]
I FIGURED IT OUT!!!!!!
it took all day yesterday and all of today until just now. I will post the issue on Stefanak's page but here is the solution for you:

/src/connection/StreamSocket.php Line 95
```php
public function read(int $length = 2048): string
    {
        $res = fread($this->stream, $length); // <-- right here... fread fails a lot and now they recommend stream_get_contents()
        if (empty($res))
            throw new ConnectException('Read error');

        if (Bolt::$debug)
            $this->printHex($res, false);

        return (string)$res;
    }
```

i replaced the line ```$res = fread($this->stream, $length);``` with ```$res =  stream_get_contents($this->stream, $length);``` and it worked like a champ.

dont really know why but i found this helpfull:
https://stackoverflow.com/questions/14664409/fread-a-lot-slower-for-downloads-than-readfile

**Comment by jonathan-rowley** [comment]
I went ahead and contacted Stefanak about the issue and he asked me to make a pull request. im sure this will get updated and will no longer be an issue on the next release. I will close this issue for now.

**Comment by transistive** [comment]
Thank you for the help and getting to the bottom of this!

That is all,

Ghlen
